---
layout: cv
title: Andie's CV
editor: 
  markdown: 
    wrap: 72
---

# Andie Razakamanana A.

::: {#webaddress}
<a href="isaac@applesdofall.org">\| andierazakamanana\@gmail.com</a> \|
<a href="http://en.wikipedia.org/wiki/Isaac_Newton">www.linkedin.com/in/andie-razakamanana-aa8486262</a>
:::

### Skills

-   Computer Skills: Word, Excel, PowerPoint, Google Slides, website
    creation.
-   Software Knowledge: Power BI, Tableau, R Studio, Programming Python,
    SQL.
-   Data Wrangling and Visualization through DS 350.
-   Learned financial accounting, managerial accounting.
-   Language: Spoke French(Native), English(Native), and
    Malagasy(Native).

### Education

**Business Analytics - Bachelors**

September 2022 - April 2026, Rexburg, Idaho

*Brigham Young University - Idaho*

-   Earned GPA of 3.78

**Social Psychology - Bachelors**

January 2014 - December 2017, Antananarivo, Madagascar

*University of Antananarivo*

## Experience

**Measurement Specialist**

*Brigham Young University Idaho*\
January 2023-Now, Rexburg, Idaho

-   Gathering and processing course evaluation data.

<!-- -->

-   Assisting with data analysis.

<!-- -->

-   Presenting Reports on findings through data analysis.

**Measurement Specialist Intern**

*Brigham Young University-Idaho*

April 21, 2025- July 23, 2025 Rexburg, Idaho

-   Analyzed data using different tools such as Power BI, R Studio,
    Excel, and shared reports following specific outlines.

**Interpreter**

*The Church of Jesus Christ of Latter-Day Saints*

March 2021 Antananarivo-Madagascar

-   Interpreted Malagasy to English technical terms for 5 church leaders
    during a conference.

## Leadership Experience

*Crossroad- Food Services BYU idaho*

**Student Lead**

September 2022 - December 2023 Rexburg

-   As a student lead, trained people to work as dishwashers and ensured
    people worked efficiently and on time.

*The Church of Jesus Christ of Latter-Day Saints*

**Missionary Leader**

January 2020 - July 2020 Congo Kinshasa East

-   Managed the responsibilities and duties of each sister missionary
    for seven months as a full-time missionary.

*The Church of Jesus Christ of Latter-Day Saints*

**Primary President**

January 2018 - August 2019 Antananarivo Madagascar

-   Directed twelve teachers in teaching of 50 children during Sunday
    school every Sunday.

## Internships

**Data Arranger**

*OMAPI, Antananarivo Madagascar*

January 2015 - February 2015

-   Registered data of new products for the company OMAPI for two
    months.

## Extra Curricular Activities

-   **Volunteer Experience:** Mormon Helping Hand. Cleaning and coloring
    school.

-   **Community Service:** Giving food and clothes to the needy.

-   **Position of Responsibility:** Teaching French and English for free
    to children.

## Hobbies and Interests

-   Love learning new skills.

-   Love watching documentaries about business.

```{=html}
<!-- ### Footer

Last updated: May 2013 -->
```
